# Generated by Django 6.0.3 on 2026-03-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
